### ISSUE TITLE
Compatibility with React Native?

### ISSUE THREAD

**Issue by kakonyitibor** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#23]
Hello,

Does anyone know if this JS SDK can be used within a React Native app?

Thank you!

**Comment by gaborszanto** [comment]
I hope someone can answer this, we're not using React Native. But I doubt that React Native has a complete high-performance JS engine with support for Web Audio inside...

**Comment by kakonyitibor** [comment]
Thanks for your reply!
I have tried out myself, and was not able to make it work.
However, this doesn't mean it's impossible, I'm not an RN expert.

**Comment by tralves** [comment]
I work with NativeScript, which works in the same principles as RN. It is not possible to use this lib in RN because the JS runtime does not include the WebAudioAPI (browser-only) and I am pretty sure Apple would block WASM from running in the JS runtime.

My approach is to embed all SP-related code in a webview, which works like a browser inside your app. That works in NativeScript and should work in RN.
